theme: jekyll-theme-cayman
title: "Leo Laugier's personal website"
description: Deep Learning PhD student
show_downloads: false
gems:
  - jekyll-seo-tag

curriculum:
  - image: img/logo-epfl-1024x576.png
    title: Swiss Federal Institute of Technology Lausanne
    info: January 2023 - Current
    place: Lausanne, Switzerland
    description: Postdoctoral researcher
    major: Neural Natural Language Processing applied to online polarization and debate analysis
    url: https://www.epfl.ch/labs/lsir/
    page: /epfl.html
  - image: img/ipparis_carre.png
    title: Polytechnic Institute of Paris
    info: June 2019 - November 2022
    place: Palaiseau, France
    description: Ph.D.
    major: Computer Science — Neural Natural Language Processing
    url: https://www.ip-paris.fr/en
    page: /ipparis.html
  - image: img/i2r_logo.png
    title: I²R - A*STAR 
    info: June 2018 - February 2019
    place: Singapore
    description: Pre-doctoral Research Engineer
    major: Deep Learning
    url: https://www.a-star.edu.sg
    page: /a-star.html
  - image: img/seal_berkeley.png
    title: University of California
    info: August 2017 - May 2018
    place: Berkeley, California
    description: MEng.
    major: Computer Science — Machine Learning and Database Systems
    url: https://www.berkeley.edu/
    page: /berkeley.html
  - image: img/ibm_logo.png
    title: IBM
    info: July 2016 
    place: Montpellier, France
    description: Intern - Data Center Technician 
    url: https://www.ibm.com/ibm/clientcenter/montpellier/index.shtml
    page: /ibm.html
  - image: img/logocs.png
    title: CentraleSupélec — University of Paris-Saclay
    info: September 2015 - May 2018
    place: Gif-sur-Yvette, France
    description: BSc. and MSc. — Dipl. Ing.
    major: Electrical Engineering, Computer Science and Telecommunications
    url: https://www.centralesupelec.fr/en
    page: /centralesupelec.html
  - image: img/lanl_logo.png
    title: Los Alamos National Laboratory
    info: July 2014 - August 2014
    place: Los Alamos, New Mexico
    description: Intern - Research Assistant
    major: Earth and Environmental Science
    url: https://www.lanl.gov/
    page: /lanl.html